const featuredProducts = [
  {
    id: "c1",
    n: "Premium Instant Coffee",
    d: "Smooth, rich instant coffee for an easy morning cup.",
    cat: "instant-coffee",
    p: 799,
    o: 999,
    r: 4.8,
    v: 124,
    b: "Bestseller",
    s: 25,
    w: "100g",
    e: "☕",
    t: "#d9bf9a",
  },
  {
    id: "c2",
    n: "Classic Arabica Instant Coffee",
    d: "A mellow classic blend.",
    cat: "instant-coffee",
    p: 649,
    o: 799,
    r: 4.6,
    v: 88,
    s: 40,
    w: "100g",
    e: "☕",
    t: "#cfae86",
  },
  {
    id: "h1",
    n: "Herbal Wellness Blend",
    d: "Made with a mix of traditional herbs.",
    cat: "herbal-products",
    p: 449,
    r: 4.5,
    v: 61,
    b: "New",
    s: 18,
    w: "150g",
    e: "🌿",
    t: "#b7c79a",
  },
  {
    id: "s1",
    n: "Organic Chia Seeds",
    d: "Versatile seeds for bowls, puddings and baking.",
    cat: "food-seeds",
    p: 349,
    o: 429,
    r: 4.7,
    v: 203,
    b: "Bestseller",
    s: 60,
    w: "250g",
    e: "🌱",
    t: "#d8c9a0",
  },
  {
    id: "s2",
    n: "Flax Seeds",
    d: "Whole flax seeds for everyday cooking.",
    cat: "food-seeds",
    p: 249,
    o: 299,
    r: 4.4,
    v: 97,
    s: 1,
    w: "250g",
    e: "🌱",
    t: "#c9b27c",
  },
  {
    id: "s3",
    n: "Mixed Super Seeds",
    d: "A pantry mix of popular seeds.",
    cat: "food-seeds",
    p: 499,
    r: 4.6,
    v: 76,
    b: "New",
    s: 32,
    w: "300g",
    e: "🌾",
    t: "#d4c58e",
  },
  {
    id: "h2",
    n: "Herbal Digestive Mix",
    d: "Traditionally enjoyed after meals.",
    cat: "herbal-products",
    p: 399,
    o: 499,
    r: 4.3,
    v: 54,
    s: 22,
    w: "100g",
    e: "🍃",
    t: "#a9bd8e",
  },
  {
    id: "m1",
    n: "Natural Honey Blend",
    d: "A golden everyday sweetener.",
    cat: "natural-sweeteners",
    p: 549,
    o: 649,
    r: 4.5,
    v: 142,
    b: "Bestseller",
    s: 15,
    w: "500g",
    e: "🍯",
    t: "#e0bd6a",
  },
];

const additionalProductGroups = [
  {
    category: "instant-coffee",
    prefix: "coffee",
    emoji: "☕",
    color: "#c9a27a",
    products: [
      [
        "Dark Roast Instant Coffee",
        "A bold, full-bodied cup with deep roasted notes.",
        699,
        "100g",
      ],
      [
        "Smooth Blend Instant Coffee",
        "A balanced blend with a smooth finish.",
        629,
        "100g",
      ],
      [
        "Espresso Style Coffee",
        "Rich coffee character for a quick espresso-style drink.",
        749,
        "100g",
      ],
      [
        "Morning Blend Coffee",
        "An easy-drinking blend for your morning routine.",
        599,
        "100g",
      ],
      [
        "Decaf Instant Coffee",
        "A smooth coffee option without the caffeine.",
        699,
        "100g",
      ],
      [
        "Gold Roast Coffee",
        "A fragrant, gently roasted instant coffee.",
        729,
        "100g",
      ],
      [
        "Coffee Taster Pack",
        "A selection of three signature instant coffee blends.",
        999,
        "3 x 50g",
      ],
      [
        "Single Origin Coffee",
        "Distinctive flavor from carefully selected coffee beans.",
        849,
        "100g",
      ],
    ],
  },
  {
    category: "herbal-products",
    prefix: "herbal",
    emoji: "🌿",
    color: "#9db18a",
    products: [
      [
        "Tulsi Herbal Blend",
        "A fragrant herbal blend featuring tulsi leaves.",
        329,
        "100g",
      ],
      [
        "Ginger Herbal Mix",
        "A warming blend with ginger and aromatic herbs.",
        349,
        "100g",
      ],
      [
        "Moringa Leaf Powder",
        "Finely milled moringa leaves for everyday recipes.",
        399,
        "100g",
      ],
      ["Neem Leaf Powder", "Dried and finely ground neem leaves.", 299, "100g"],
      [
        "Amla Herbal Powder",
        "Tangy amla powder for drinks and recipes.",
        349,
        "100g",
      ],
      [
        "Calm Evening Herbal Blend",
        "A mellow herbal mix for a quiet evening ritual.",
        429,
        "100g",
      ],
      [
        "Lemongrass Herbal Mix",
        "Bright lemongrass with a clean citrus aroma.",
        379,
        "100g",
      ],
    ],
  },
  {
    category: "herbal-tea",
    prefix: "tea",
    emoji: "🍵",
    color: "#b7c79a",
    products: [
      [
        "Tulsi Green Tea",
        "Green tea leaves blended with aromatic tulsi.",
        399,
        "100g",
      ],
      [
        "Chamomile Herbal Tea",
        "A gentle floral infusion for any time of day.",
        449,
        "50g",
      ],
      [
        "Peppermint Leaf Tea",
        "A refreshing caffeine-free peppermint infusion.",
        379,
        "50g",
      ],
      [
        "Lemongrass Tea",
        "A bright, citrusy herbal cup with lemongrass.",
        349,
        "75g",
      ],
      [
        "Hibiscus Flower Tea",
        "Tart hibiscus petals for a vivid herbal brew.",
        429,
        "75g",
      ],
      [
        "Ginger Lemon Tea",
        "A zesty blend of ginger and citrus notes.",
        399,
        "100g",
      ],
      ["Green Tea Classic", "A clean, mellow everyday green tea.", 449, "100g"],
    ],
  },
  {
    category: "food-seeds",
    prefix: "seed",
    emoji: "🌱",
    color: "#d8c38f",
    products: [
      [
        "Pumpkin Seeds",
        "Crunchy pumpkin seeds for snacks and toppings.",
        329,
        "200g",
      ],
      [
        "Sunflower Seeds",
        "Versatile sunflower seeds for salads and baking.",
        279,
        "200g",
      ],
      [
        "Black Sesame Seeds",
        "Nutty black sesame seeds for sweet and savory dishes.",
        249,
        "200g",
      ],
      [
        "White Sesame Seeds",
        "Classic sesame seeds for cooking and baking.",
        229,
        "200g",
      ],
      [
        "Watermelon Seeds",
        "Mild, crunchy seeds for snacks and trail mixes.",
        299,
        "200g",
      ],
      ["Basil Seeds", "Tiny basil seeds for drinks and desserts.", 249, "200g"],
      [
        "Hemp Seeds",
        "Soft, nutty hemp seeds for bowls and smoothies.",
        499,
        "150g",
      ],
      [
        "Roasted Seed Mix",
        "A lightly roasted mix for convenient snacking.",
        399,
        "200g",
      ],
    ],
  },
  {
    category: "healthy-foods",
    prefix: "food",
    emoji: "🥣",
    color: "#c7b38a",
    products: [
      [
        "Rolled Oats",
        "Whole rolled oats for breakfast and baking.",
        249,
        "500g",
      ],
      [
        "Steel Cut Oats",
        "Hearty cut oats with a pleasantly chewy texture.",
        299,
        "500g",
      ],
      [
        "Organic Quinoa",
        "A versatile grain for salads and warm bowls.",
        449,
        "400g",
      ],
      [
        "Millet Breakfast Mix",
        "A simple grain blend for warm breakfast bowls.",
        349,
        "400g",
      ],
      [
        "Raw Almonds",
        "Whole almonds for snacking and home recipes.",
        599,
        "250g",
      ],
      [
        "Raw Cashews",
        "Creamy whole cashews for snacks and cooking.",
        649,
        "250g",
      ],
      [
        "Trail Mix",
        "A convenient mix of nuts, seeds and dried fruit.",
        449,
        "250g",
      ],
    ],
  },
  {
    category: "natural-sweeteners",
    prefix: "sweetener",
    emoji: "🍯",
    color: "#e0b35c",
    products: [
      [
        "Wildflower Honey",
        "Golden honey with a delicate floral taste.",
        599,
        "500g",
      ],
      [
        "Raw Forest Honey",
        "Distinctive honey with a rich, deep flavor.",
        699,
        "500g",
      ],
      [
        "Coconut Sugar",
        "A caramel-toned alternative for drinks and baking.",
        349,
        "300g",
      ],
      [
        "Date Syrup",
        "A smooth fruit syrup for porridge and desserts.",
        399,
        "300g",
      ],
      [
        "Organic Jaggery Powder",
        "A traditional unrefined sweetener for recipes.",
        249,
        "500g",
      ],
    ],
  },
  {
    category: "spices-herbs",
    prefix: "spice",
    emoji: "🌶",
    color: "#b98a5e",
    products: [
      [
        "Turmeric Powder",
        "Warm, earthy turmeric for everyday cooking.",
        249,
        "200g",
      ],
      [
        "Ceylon Cinnamon",
        "Sweet, aromatic cinnamon for drinks and baking.",
        299,
        "100g",
      ],
      [
        "Ground Ginger",
        "Fragrant ground ginger for savory and sweet dishes.",
        229,
        "100g",
      ],
      [
        "Ground Black Pepper",
        "Freshly aromatic pepper for daily seasoning.",
        279,
        "100g",
      ],
      [
        "Cumin Seeds",
        "Earthy whole cumin seeds for tempering and spice blends.",
        199,
        "200g",
      ],
      [
        "Coriander Powder",
        "Mellow ground coriander for curries and marinades.",
        199,
        "200g",
      ],
    ],
  },
  {
    category: "gift-sets",
    prefix: "gift",
    emoji: "🎁",
    color: "#a9b79a",
    products: [
      [
        "Coffee Lover Gift Set",
        "A thoughtful set of coffee favorites for gifting.",
        1299,
        "3 items",
      ],
      [
        "Herbal Tea Gift Set",
        "A curated collection of herbal tea blends.",
        1199,
        "3 items",
      ],
      [
        "Everyday Wellness Gift Box",
        "Herbal favorites packed together for a special gift.",
        1499,
        "4 items",
      ],
      [
        "Seeds and Grains Gift Set",
        "A pantry-ready selection of seeds and grains.",
        999,
        "4 items",
      ],
    ],
  },
];

const additionalProducts = additionalProductGroups.flatMap((group) =>
  group.products.map(([name, description, price, weight], index) => ({
    id: `${group.prefix}-${String(index + 1).padStart(2, "0")}`,
    n: name,
    d: description,
    cat: group.category,
    p: price,
    r: Number((4.2 + ((index + group.prefix.length) % 8) / 10).toFixed(1)),
    v: 30 + index * 11,
    s: 12 + index * 3,
    w: weight,
    e: group.emoji,
    t: group.color,
  })),
);

export const P = [...featuredProducts, ...additionalProducts];

export const C = [
  ["Instant Coffee", "#c9a27a", "☕", "instant-coffee"],
  ["Herbal Products", "#9db18a", "🌿", "herbal-products"],
  ["Herbal Tea", "#b7c79a", "🍵", "herbal-tea"],
  ["Food Seeds", "#d8c38f", "🌱", "food-seeds"],
  ["Healthy Foods", "#c7b38a", "🥣", "healthy-foods"],
  ["Natural Sweeteners", "#e0b35c", "🍯", "natural-sweeteners"],
  ["Spices & Herbs", "#b98a5e", "🌶", "spices-herbs"],
  ["Gift Sets", "#a9b79a", "🎁", "gift-sets"],
];
